### PR TITLE
Fix local development with Pub/Sub Emulator

### LINKED ISSUE #46: Support for Receiving Messages From PubSub Emulator?
Maybe I just have things setup improperly, but it appears that a request from the PubSub emulator is not formatted in a way that the function framework handles?

For example, if I send a JSON Payload as:

```json
{
    "data":"<base64 encoded>"
}
```

The functions framework will do the right thing and all is well.  However when I set a PubSub Emulator Subscription endpoint things are not well:

Those payloads come across the wire shaped like this:

```json
{
      "subscription": "projects/local-project/subscriptions/local-test",
      "message": {
        "data": "<base64 string>",
        "messageId": "7",
        "attributes": {
          "key": "value"
        }
    }
}
```

Note the `message` is embedded in an object envelope.

Is there a way to have the functions framework when registering the function with:

```go
funcframework.RegisterEventFunctionContext(ctx, "/", action)
```

handle these types of requests?

### PR DESCRIPTION
**Pull request by anniefu**
This mirrors the fix for local development from the Node.js (GoogleCloudPlatform/functions-framework-nodejs#272) and Python (GoogleCloudPlatform/functions-framework-python#121) repos.

Background from those PRs:
"Currently, deploying a function with --trigger-topic creates a Pub/Sub subscription that delivers events to an internal endpoint that marshals request payloads before forwarding them to a user's function. Unfortunately, this breaks local development with the Pub/Sub emulator as the Functions Frameworks are dependent on this request marshalling logic.

In order to better support local development and testing with the Pub/Sub emulator, this commit introduces the event marshalling logic to the Functions Framework via express middleware that is enable when the PUBSUB_EMULATOR_HOST is set."

Fixes #46

### CODE REVIEW

**Review by mtraver — CHANGES_REQUESTED** [review]

File: funcframework/events_test.go [hunk 1]
```diff
@@ -148,31 +145,59 @@ func TestGetBackgroundEvent(t *testing.T) {
...
+					}
+				}
+			}`),
+			metadata: &metadata.Metadata{
+				EventID:   "1",
+				EventType: "google.pubsub.topic.publish",
+				Resource: &metadata.Resource{
+					Name: "projects/sample-project/topics/gcf-test",
+					Type:    "type.googleapis.com/google.pubusb.v1.PubsubMessage",
+					Service: "pubsub.googleapis.com",
```
[the remark this answers is not in the document]
Comment (anniefu) [reply funcframework/events_test.go]: Done. Normally vscode handles formatting for me but for some reason my extension's not working :/

File: funcframework/events.go [hunk 2]
```diff
@@ -83,20 +85,34 @@ var (
...
+	// Attempt to unmarshal into one of the known background event types.
+	possible := possibleEvents{}
+	if err := json.Unmarshal(body, &possible); err != nil {
 		return nil, nil, err
 	}
 
+	event := possible.BackgroundEvent
+	// If the background event payload is missing, check if it's a legacy
+	// Pub/Sub event.
+	if possible.BackgroundEvent == nil && possible.LegacyEvent != nil {
```
Comment (matthewrobertson) [inline funcframework/events.go:106]: nit: I think `LegacyEvent` isn't a great name for this because, at this point, it isn't clear that this logic is specific to PubSub. Maybe give the fields in the `possibleEvents` struct names?

**Comment by matthewrobertson** [comment]
Overall LGTM. Main thing is to add the timestamp to maintain consistency with other languages.

**Review by matthewrobertson — CHANGES_REQUESTED** [review]

File: internal/events/pubsub/pubsub.go [hunk 3]
```diff
@@ -0,0 +1,70 @@
...
+
+const (
+	pubsubEventType   = "google.pubsub.topic.publish"
+	pubsubMessageType = "type.googleapis.com/google.pubusb.v1.PubsubMessage"
+	pubsubService     = "pubsub.googleapis.com"
+)
+
+// LegacyEvent represents the legacy event payload that is sent by
+// Pub/Sub to Background Functions (https://cloud.google.com/functions/docs/writing/background).
+type LegacyEvent struct {
```
Comment (matthewrobertson) [inline internal/events/pubsub/pubsub.go:21]: I think `LegacyEvent` is a bit of an overloaded term because we also use it to distinguish between CloudEvents. Cloud we call this something else e.g. `RawPubSubEvent`

**Comment by matthewrobertson** [comment]
One more thing: this FF already supports upcasting GCF events to CloudEvents so with this change it should be possible to directly from PubSub emulator => CloudEvent. Cloud you add a test that covers that?

File: funcframework/events_test.go [hunk 4]
```diff
@@ -134,45 +134,142 @@ func TestGetBackgroundEvent(t *testing.T) {
...
-				t.Errorf("incorrect metadata, got %+v, want %+v", md, tc.metadata)
+			// If timestamp is not being tested in this test case, skip comparing the field
+			// since some timestamps are auto-populated with time.Now()
+			diffOpts := []cmp.Option{}
+			if tc.wantMetadata != nil && tc.wantMetadata.Timestamp.IsZero() {
+				diffOpts = append(diffOpts, cmpopts.IgnoreFields(metadata.Metadata{}, "Timestamp"))
+			}
+
+			if diff := cmp.Diff(tc.wantMetadata, md, diffOpts...); diff != "" {
+				t.Errorf("MakeGatewayInfo() mismatch (-want +got):\n%s", diff)
```
Comment (mtraver) [inline funcframework/events_test.go:268]: Is `MakeGatewayInfo` a typo?

File: internal/events/pubsub/pubsub_test.go [hunk 5]
```diff
@@ -0,0 +1,226 @@
...
+			name: "extra prefix",
+			path: "http://localhost:8080/extra/prefix/projects/abc/topics/topic",
+			want: "projects/abc/topics/topic",
+		}, {
+			name: "from pubsub",
+			path: "https://fake-tp.appspot.com/_ah/push-handlers/pubsub/projects/abc/topics/topic",
+			want: "projects/abc/topics/topic",
+		}, {
+			name: "with parameters",
+			path: "https://fake-tp.appspot.com/_ah/push-handlers/pubsub/projects/abc/topics/topic?pubsub_trigger=true",
```
[the remark this answers is not in the document]
Comment (anniefu) [reply internal/events/pubsub/pubsub_test.go:42]: I passed the "request.URL.Path" field which I think does include the domain name according to the docs: https://golang.org/pkg/net/url/#URL

File: funcframework/events.go (hunk 2 above)
Comment (anniefu) [reply funcframework/events.go]: There wasn't a great way to include fieldnames because the way the `json` library works, it automatically expects field names to be present in the JSON. But at least the new "LegacyPushSubscriptionEvent" field name heavily implies that it's a Pub/Sub related.

File: funcframework/events_test.go (hunk 4 above)
Comment (anniefu) [reply funcframework/events_test.go]: Oh, yeah. It's the example from the cmp.Diff docs :)

File: internal/events/pubsub/pubsub.go (hunk 3 above)
Comment (anniefu) [reply internal/events/pubsub/pubsub.go]: I renamed this to "LegacyPushSubscriptionEvent" and made the comment more descriptive. I kept Legacy because that's how the [Cloud Functions docs ](https://cloud.google.com/functions/docs/calling/pubsub#legacy_cloud_pubsub_triggers) refer to them.

I didn't include PubSub in the struct name because golang has a naming convention to avoid "stuttering": https://blog.golang.org/package-names#TOC_3.

**Comment by anniefu** [comment]
> One more thing: this FF already supports upcasting GCF events to CloudEvents so with this change it should be possible to directly from PubSub emulator => CloudEvent. Cloud you add a test that covers that?

I think this is best done in another PR, there's some logic in the conversion to CloudEvents that deals with Pub/Sub that can probably be removed? But I don't want to mix too many things into this one PR.

**Comment by anniefu** [comment]
Bump on this when you get a chance @matthewrobertson @mtraver

**Review by matthewrobertson — APPROVED** [review]
LGTM!

**Review by mtraver — APPROVED** [review]
