### PR TITLE
fix: Allow registering multiple functions with one server for local testing.

### LINKED ISSUE #109: Serving multiple functions locally from a single server instance
When #95 was merged, the ability to serve several functions from one instance locally broke. I'm not sure whether it was ever intended to be possible, but since it was, we've been relying on it.

Let me elaborate just a bit. We have a single project from which we deploy 4 separate functions to Cloud Run. For convenience, in our local dev environments, we serve them all from a single server and port by registering each function with a separate call to `funcframework.RegisterHTTPFunctionContext` (previously `funcframework.RegisterHTTPFunction`).

This was possible in 1.2.0 (yep, I've missed a few versions 😊), but broke when I upgraded to the most recent version.

It's still possible by passing an `http.ServeMux` to `funcframework.RegisterHTTPFunctionContext` or `functions.HTTP`, but that seems more of a "chaotic lawful" solution than an actual solution.

### PR DESCRIPTION
**Pull request by jihuin**
There are two ways to test multiple functions within one server. 

1. Declaratively register multiple functions (e.g. calling `functions.HTTP()`) and run `go run cmd/main.go` without setting the env var `FUNCTION_TARGET`. In this case, all registered functions will be served  at "/{func_name}".
2. Manually register the handers (e.g. calling `funcframework.RegisterHTTPFunctionContext()`)  and run `go run cmd/main.go` without setting the env var `FUNCTION_TARGET`. In this case, only the registered handlers will be served at the user defined path.

Closes #109

### CODE REVIEW

File: funcframework/framework.go [hunk 1]
```diff
@@ -97,61 +99,95 @@ func RegisterHTTPFunctionContext(ctx context.Context, path string, fn func(http.
...
-			server, err := wrapHTTPFunction("/", fn.HTTPFn)
-			if err != nil {
-				return fmt.Errorf("unexpected error in registerHTTPFunction: %v", err)
-			}
-			handler = server
-		} else if fn.CloudEventFn != nil {
-			server, err := wrapCloudEventFunction(ctx, "/", fn.CloudEventFn)
+func initServer() error {
+	target := os.Getenv("FUNCTION_TARGET")
+	switch {
```
Comment (anniefu) [inline funcframework/framework.go:130]: I think this is better off as an if-else condition than a switch case. It's pretty confusing whether `handlerRegistered` or `len(target) > 0` will get evaluated first and comes down to a Golang specific implementation of switch cases (in other languages, it's not guaranteed that the cases are checked top-to-bottom).

File: funcframework/framework.go [hunk 2]
```diff
@@ -97,61 +99,95 @@ func RegisterHTTPFunctionContext(ctx context.Context, path string, fn func(http.
...
+	// If FUNCTION_TARGET is set, only serve this target function.
+	case len(target) > 0:
+		// Start a new server because the same route "/" can only be
```
Comment (anniefu) [inline funcframework/framework.go:133]: Can we avoid this problem by deferring `server.Handle` call until this function? We can keep a file-global `handlerPath` or something instead of `handlerRegistered`?

File: funcframework/framework.go [hunk 3]
```diff
@@ -97,61 +99,95 @@ func RegisterHTTPFunctionContext(ctx context.Context, path string, fn func(http.
...
+	// Serve all the registered functions.
+	default:
+		server = http.NewServeMux()
+		handlerRegistered = false
+		fns := registry.Default().GetAllRegisteredFunction()
+		for funcName := range fns {
+			h, err := wrapFunction(funcName)
 			if err != nil {
-				return fmt.Errorf("unexpected error in registerCloudEventFunction: %v", err)
+				fmt.Printf("Failed to serve function %s: %v", funcName, err)
```
Comment (anniefu) [inline funcframework/framework.go:153]: I think this is ok to be an error that fails server startup. The user would have had to register the function, so they intended for it to be servable.

File: funcframework/framework.go [hunk 4]
```diff
@@ -97,61 +99,95 @@ func RegisterHTTPFunctionContext(ctx context.Context, path string, fn func(http.
...
+		server.Handle("/", h)
+	// If any handlers are registered, only serve these registered handlers.
+	case handlerRegistered:
+		// No-op because the handlers are already registered with the server.
+	// Serve all the registered functions.
+	default:
+		server = http.NewServeMux()
+		handlerRegistered = false
+		fns := registry.Default().GetAllRegisteredFunction()
+		for funcName := range fns {
```
Comment (anniefu) [inline funcframework/framework.go:150]: seems like you can use the value of this map instead of having to call `GetRegisteredFunction(name)` for each one in the helper function?

File: funcframework/framework.go [hunk 5]
```diff
@@ -86,9 +87,10 @@ func RegisterEventFunction(path string, fn interface{}) {
 
 // RegisterHTTPFunctionContext registers fn as an HTTP function.
 func RegisterHTTPFunctionContext(ctx context.Context, path string, fn func(http.ResponseWriter, *http.Request)) error {
```
Comment (anniefu) [inline funcframework/framework.go:89]: Hmm... I wonder if the logic for all this would be more straightforward if we just changed these functions to call registry.HTTP() and added a path field to `RegisteredFunction`...

**Review by anniefu — CHANGES_REQUESTED** [review]

File: internal/registry/registry.go [hunk 6]
```diff
@@ -65,3 +65,8 @@ func (r *Registry) GetRegisteredFunction(name string) (RegisteredFunction, bool)
 	fn, ok := r.functions[name]
 	return fn, ok
 }
+
+// GetAllRegisteredFunction returns all the registered functions.
+func (r *Registry) GetAllRegisteredFunction() map[string]RegisteredFunction {
```
[the remark this answers is not in the document]
Comment (jihuin) [reply internal/registry/registry.go]: Done.

File: funcframework/framework.go [hunk 7]
```diff
@@ -86,72 +82,98 @@ func RegisterEventFunction(path string, fn interface{}) {
...
-	server, err := wrapHTTPFunction(path, fn)
-	if err == nil {
-		handler = server
+	if err := registry.Default().RegisterHTTP(path, fn, registry.WithPath(path)); err != nil {
```
Comment (anniefu) [inline funcframework/framework.go:85]: Oh I kind of forgot these didn't have names... Maybe we should give it a readable name like `fmt.Sprintf("function at path %q", path)` or something so that error messages that print the function name won't look as weird.

File: funcframework/framework_test.go [hunk 8]
```diff
@@ -586,49 +609,55 @@ func TestCloudEventFunction(t *testing.T) {
 
 func TestDeclarativeFunctionHTTP(t *testing.T) {
 	funcName := "httpfunc"
+	funcResp := "Hello World!"
 	os.Setenv("FUNCTION_TARGET", funcName)
+	defer os.Unsetenv("FUNCTION_TARGET")
 
-	if err := RegisterHTTPFunctionContext(context.Background(), "/", func(w http.ResponseWriter, r *http.Request) {
```
Comment (anniefu) [inline funcframework/framework_test.go:591]: I think we still want to have some test that mixes both the older RegisterHTTPFunctionContext and `functions.HTTP` calls and makes sure things work as expected.

**Review by anniefu — APPROVED** [review]
Nice, thanks for the major refactor! This makes all the code a lot cleaner now.

File: funcframework/framework.go (hunk 5 above)
Comment (jihuin) [reply funcframework/framework.go:84]: Done.

File: funcframework/framework.go (hunk 7 above)
Comment (jihuin) [reply funcframework/framework.go]: Done.

File: funcframework/framework_test.go (hunk 8 above)
Comment (jihuin) [reply funcframework/framework_test.go:591]: Done

File: internal/registry/registry.go [hunk 9]
```diff
@@ -12,8 +12,19 @@ import (
 // registered with the registry.
 type RegisteredFunction struct {
 	Name         string                                         // The name of the function
+	Path         string                                         // The serving path of the function
 	CloudEventFn func(context.Context, cloudevents.Event) error // Optional: The user's CloudEvent function
 	HTTPFn       func(http.ResponseWriter, *http.Request)       // Optional: The user's HTTP function
+	EventFn      interface{}                                    // Optional: The user's Event function
+}
+
+// Option is
```
[the remark this answers is not in the document]
Comment (jihuin) [reply internal/registry/registry.go]: Done. Thanks for catching this.

File: funcframework/framework.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (jihuin) [reply funcframework/framework.go]: Done.

File: funcframework/framework.go [hunk 10]
```diff
@@ -86,72 +82,98 @@ func RegisterEventFunction(path string, fn interface{}) {
...
+		return fmt.Errorf("failed to register function at path %s: %s", path, err)
```
[the remark this answers is not in the document]
Comment (jihuin) [reply funcframework/framework.go]: The function name is included so it should be fine. Changed %s to %q
